- name: generate-snake-game-from-github-contribution-grid
  # You may pin to the exact commit or the version.
  # uses: Platane/snk@aebc3a92857730857d5a96010a3538f16bbec662
  uses: Platane/snk@v3.0.0
  with: ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
  github_user_name: beunori
